### ISSUE TITLE
How Can I fix cannot import name 'Client' from 'spyse'

### ISSUE THREAD

**Issue by BlackArcheruz** [zeropwn/spyse.py#10]
I just installed theHarvester on my Laptop and it required to me install spyse.py and I installed it, and I get this error: 
`cannot import name 'Client' from 'spyse' (/home/muhammadsiddiq/.local/lib/python3.9/site-packages/spyse/__init__.py)
sys:1: RuntimeWarning: coroutine 'start.<locals>.store' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
`
How Can I fix it ?

**Comment by touhidulshawan** [comment]
So, what's the solution of this error?

**Comment by Curwen98** [comment]
any solution??? I can't fix it

**Comment by Kyrlio** [comment]
try this `pip3 install spyse-python`
