### ISSUE TITLE
some issues with domains not being found

### ISSUE THREAD

**Issue by soupnatzi** [zeropwn/spyse.py#3]
when i run aquatone with spyse it does not return domains..

spyse -target starbucks.com -param domain --subdomains --raw | aquatone
aquatone v1.7.0 started at 2019-10-05T11:33:50-04:00

No targets found in input.
wondering if i could get some help on this.

**Comment by soupnatzi** [comment]
spyse -target google.com -param domain --subdomains --raw | aquatone
aquatone v1.7.0 started at 2019-10-05T11:36:45-04:00

No targets found in input.
Traceback (most recent call last):
  File "/usr/local/bin/spyse", line 410, in <module>
    print(get_subdomains_aggregate(args.target, param, page, raw=args.raw))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by soupnatzi** [comment]
when i run spyse -target google.com --subdomains it returns subdomains.

**Comment by zeropwn** [comment]
This is more of an issue on Aquatone's end rather than spyse.py's.
Does it work for you when you try this:
```bash
spyse -target google.com --subdomains | aquatone
```
My assumption here is that the JSON formatting when using the ```--raw``` flag confuses Aquatone. Not entirely sure though, will look into this more.

**Comment by soupnatzi** [comment]
running spyse -target google.com --subdomains | aquatone does work fine so i am guessing it is aquatone being confused with --raw flag

**Comment by soupnatzi** [comment]
is there a flag to run a file with a list of subdomains i did not see it when i ran help?
